# Basic Information 
title: Brian (Guangzhi) Sun
position: Junior Research Fellow
affiliation: University of Cambridge
affiliation_link: https://www.cam.ac.uk/
affiliation_logo: ./assets/img/university-logo-small-horizontal-white-156eae9527.svg
email: gs534 (at) cam.ac.uk

# Search Engine Optimization (SEO)
keywords: brian sun, guangzhi sun, briansun, sun guangzhi
canonical: https://briansidp.github.io/brian-sun.github.io/
description: Brian Sun is a research associate at University of Cambridge. His research lies in speech recognition and conversational AI.

# The option is used to enable the Johns Hopkins template.
# enable_hopkins_logo: true
enable_hopkins_logo: false

# The option is used to show the last update time.
# enable_last_update: false
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=PzPAzf8AAAAJ&hl=en
cv_link: ./assets/supplements/2_page_CV.pdf
github_link: https://github.com/BriansIDP
linkedin: https://www.linkedin.com/in/brian-sun-59746b12b/?originalSubdomain=uk
twitter: 

# Images 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# # Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
